### ISSUE TITLE
App crashes when a user deletes the selected color using the `-` button

### ISSUE THREAD

**Issue by rafaeltab** [primer/prism#19]
**Describe the bug**
App crashes when a user deletes the selected color using the `-` button

**To Reproduce**
1. Go to https://primer.style/prism/.
2. Create a palette.
3. Select a scale.
4. Select the last color in the scale.
5. Click the `-` button.

**Expected behavior**
The color that is now the latest after deletion should be selected

**Actual behavior**
The website presents a completely white screen, and the application throws the following error.

```
VM1050 react_devtools_backend.js:4026 Error: Failed to parse color: ""
    at g (parseToRgba.ts:51:3)
    at B (getLuminance.ts:18:21)
    at _ (getContrast.ts:11:22)
    at Be (scale.tsx:497:31)
    at oi (react-dom.production.min.js:157:137)
    at Fi (react-dom.production.min.js:180:154)
    at $u (react-dom.production.min.js:269:343)
    at Tc (react-dom.production.min.js:250:347)
    at jc (react-dom.production.min.js:250:278)
    at kc (react-dom.production.min.js:250:138)
overrideMethod @ VM1050 react_devtools_backend.js:4026
uu @ react-dom.production.min.js:216
a.componentDidCatch.n.callback @ react-dom.production.min.js:217
da @ react-dom.production.min.js:131
hu @ react-dom.production.min.js:220
Cc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vo @ react-dom.production.min.js:122
_c @ react-dom.production.min.js:252
bc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vo @ react-dom.production.min.js:122
qo @ react-dom.production.min.js:123
Ko @ react-dom.production.min.js:122
Le @ react-dom.production.min.js:292
Xt @ react-dom.production.min.js:73
VM1050 react_devtools_backend.js:4026 Error: Failed to parse color: ""
    at g (parseToRgba.ts:51:3)
    at B (getLuminance.ts:18:21)
    at _ (getContrast.ts:11:22)
    at Be (scale.tsx:497:31)
    at oi (react-dom.production.min.js:157:137)
    at Fi (react-dom.production.min.js:180:154)
    at $u (react-dom.production.min.js:269:343)
    at Tc (react-dom.production.min.js:250:347)
    at jc (react-dom.production.min.js:250:278)
    at kc (react-dom.production.min.js:250:138)
overrideMethod @ VM1050 react_devtools_backend.js:4026
uu @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
da @ react-dom.production.min.js:131
hu @ react-dom.production.min.js:220
Cc @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vo @ react-dom.production.min.js:122
_c @ react-dom.production.min.js:252
bc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vo @ react-dom.production.min.js:122
qo @ react-dom.production.min.js:123
Ko @ react-dom.production.min.js:122
Le @ react-dom.production.min.js:292
Xt @ react-dom.production.min.js:73
parseToRgba.ts:51 Uncaught Error: Failed to parse color: ""
    at g (parseToRgba.ts:51:3)
    at B (getLuminance.ts:18:21)
    at _ (getContrast.ts:11:22)
    at Be (scale.tsx:497:31)
    at oi (react-dom.production.min.js:157:137)
    at Fi (react-dom.production.min.js:180:154)
    at $u (react-dom.production.min.js:269:343)
    at Tc (react-dom.production.min.js:250:347)
    at jc (react-dom.production.min.js:250:278)
    at kc (react-dom.production.min.js:250:138)
g @ parseToRgba.ts:51
B @ getLuminance.ts:18
_ @ getContrast.ts:11
Be @ scale.tsx:497
oi @ react-dom.production.min.js:157
Fi @ react-dom.production.min.js:180
$u @ react-dom.production.min.js:269
Tc @ react-dom.production.min.js:250
jc @ react-dom.production.min.js:250
kc @ react-dom.production.min.js:250
bc @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Vo @ react-dom.production.min.js:122
qo @ react-dom.production.min.js:123
Ko @ react-dom.production.min.js:122
Le @ react-dom.production.min.js:292
Xt @ react-dom.production.min.js:73
```

This error is very similar to #10, but not completely since in #10 all the colors have to be deleted.
Pull request #15 does fix issue #10, but not this one.

**Environment**
 - OS: Windows 10 21H1 Build 19043.1766
 - Browser:  Chrome 102.0.5005.115

**Comment by colebemis** [comment]
Great catch. Thank you for reporting this! 

@rafaeltab or @pavelkeyzik: Want to try fixing this?

**Comment by rafaeltab** [comment]
I sadly don't have time to fix this right now.

**Comment by pavelkeyzik** [comment]
@colebemis Sure! I'll take this one 😊

**Comment by pavelkeyzik** [comment]
Hey @rafaeltab 👋 The issue has been fixed and you can check this here https://primer.style/prism. If you're happy with the result, you can close the issue 😊

**Comment by rafaeltab** [comment]
This issue seems to be solved, but I managed to crash it using the 'Delete color' button to delete the last present color. 
I'll post a comment in #10

**Comment by pavelkeyzik** [comment]
@rafaeltab I think you can just create a new issue, as #10 is already closed 😊
